-- 코드를 입력하세요
SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    CAST(c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100.0) * 30 AS UNSIGNED) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR c
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON c.CAR_TYPE = d.CAR_TYPE AND d.DURATION_TYPE = '30일 이상'
WHERE
    c.CAR_TYPE IN ('세단', 'SUV')
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (
            END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
        )
    )
    AND (c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100.0) * 30) >= 500000
    AND (c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100.0) * 30) < 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;
